export const GET_EVENTS_PENDING = 'GET_EVENTS_PENDING'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED'

export const GET_ONE_EVENT_PENDING = 'GET_ONE_EVENT_PENDING'
export const GET_ONE_EVENT_SUCCESS = 'GET_ONE_EVENT_SUCCESS'
export const GET_ONE_EVENT_FAILED = 'GET_ONE_EVENT_FAILED'

export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAILED = 'ADD_EVENT_FAILED'

export const EDIT_EVENT_PENDING = 'EDIT_EVENT_PENDING'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED'

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED'