export const GET_TEAMS_PENDING = 'GET_TEAMS_PENDING'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAILED = 'GET_TEAMS_FAILED'

export const GET_ONE_TEAM_PENDING = 'GET_ONE_TEAM_PENDING'
export const GET_ONE_TEAM_SUCCESS = 'GET_ONE_TEAM_SUCCESS'
export const GET_ONE_TEAM_FAILED = 'GET_ONE_TEAM_FAILED'

export const ADD_TEAM_PENDING = 'ADD_TEAM_PENDING'
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS'
export const ADD_TEAM_FAILED = 'ADD_TEAM_FAILED'

export const EDIT_TEAM_PENDING = 'EDIT_TEAM_PENDING'
export const EDIT_TEAM_SUCCESS = 'EDIT_TEAM_SUCCESS'
export const EDIT_TEAM_FAILED = 'EDIT_TEAM_FAILED'

export const DELETE_TEAM_PENDING = 'DELETE_TEAM_PENDING'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAILED = 'DELETE_TEAM_FAILED'